name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, xml, ctype, json, bcmath, pdo_pgsql
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction
      - name: PHP Syntax Check
        run: |
          find app routes database -name "*.php" -print0 | xargs -0 -n1 php -l
      - name: Laravel Pint
        run: ./vendor/bin/pint --test